directories:
  - ~/Dropbox (Feram)/Feram Team Folder/tasks
  - ~/Tasks

views:
  - name: Overdue, ☐, ⬆ By ⏳
    filter: !!js/function |
      function (task) {
        return !task.isClosed && task.dueDate
          ? task.dueDate < new Date()
          : false
      }
    sort: !!js/function |
      function (taskA, taskB) {
        if (!taskA.dueDate && taskB.dueDate) return 1
        if (taskA.dueDate && !taskB.dueDate) return -1
        return taskA.dueDate - taskB.dueDate
      }
    map: !!js/function |
      function (task) {
        return task
      }

  - name: With Due Date, ☐, ⬆ By ⏳
    filter: !!js/function |
      function (task) {
        return !task.isClosed && task.hasOwnProperty('dueDate')
      }
    sort: !!js/function |
      function (taskA, taskB) {
        if (!taskA.dueDate && taskB.dueDate) return 1
        if (taskA.dueDate && !taskB.dueDate) return -1
        return taskA.dueDate - taskB.dueDate
      }

  - name: Next 10 Days, ☐, ⬆ By ⏳
    filter: !!js/function |
      function (task) {
        const now = new Date()
        const inTenDays = new Date()
          .setDate(now.getDate() + 10)
        return !task.isClosed &&
          task.hasOwnProperty('dueDate') &&
          (task.dueDate < inTenDays) &&
          (now < task.dueDate)
      }
    sort: !!js/function |
      function (taskA, taskB) {
        if (!taskA.dueDate && taskB.dueDate) return 1
        if (taskA.dueDate && !taskB.dueDate) return -1
        return taskA.dueDate - taskB.dueDate
      }

  - name: ☑, ⬆ By ⏳
    filter: !!js/function |
      function (task) {
        return task.isClosed
      }
    sort: !!js/function |
      function (taskA, taskB) {
        if (!taskA.dueDate && taskB.dueDate) return 1
        if (taskA.dueDate && !taskB.dueDate) return -1
        return taskA.dueDate - taskB.dueDate
      }

  - name: ☐, ⬆ By ⏳
    filter: !!js/function |
      function (task) {
        return !task.isClosed
      }
    sort: !!js/function |
      function (taskA, taskB) {
        if (!taskA.dueDate && taskB.dueDate) return 1
        if (taskA.dueDate && !taskB.dueDate) return -1
        return taskA.dueDate - taskB.dueDate
      }

  - name: Assigned to Me, ☐, ⬆ By ⏳
    filter: !!js/function |
      function (task) {
        const name = 'Adrian Sieber'
        return !task.isClosed &&
          task.assignee &&
          task.assignee.name === name
      }
    sort: !!js/function |
      function (taskA, taskB) {
        if (!taskA.dueDate && taskB.dueDate) return 1
        if (taskA.dueDate && !taskB.dueDate) return -1
        return taskA.dueDate - taskB.dueDate
      }
